### ISSUE TITLE
Cannot Load the Nodes，metoo

### ISSUE THREAD

**Issue by ljn00001** [natto-maki/ComfyUI-NegiTools#6] opened 2023-12-29 07:18 UTC
Traceback (most recent call last):
  File "D:\AIGC\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AIGC\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools\__init__.py", line 8, in <module>
    from .negi.open_pose_to_point_list import OpenPoseToPointList
  File "D:\AIGC\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\open_pose_to_point_list.py", line 6, in <module>
    from .repos.controlnet_aux.src.controlnet_aux import OpenposeDetector
  File "D:\AIGC\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\repos\controlnet_aux\src\controlnet_aux\__init__.py", line 4, in <module>
    from .leres import LeresDetector
  File "D:\AIGC\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\repos\controlnet_aux\src\controlnet_aux\leres\__init__.py", line 13, in <module>
    from .pix2pix.models.pix2pix4depth_model import Pix2Pix4DepthModel
ModuleNotFoundError: No module named 'ComfyUI-NegiTools.negi.repos.controlnet_aux.src.controlnet_aux.leres.pix2pix.models'

Cannot import D:\AIGC\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools module for custom nodes: No module named 'ComfyUI-NegiTools.negi.repos.controlnet_aux.src.controlnet_aux.leres.pix2pix.models'
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR:

**Comment by ParticleDog** [comment] 2024-01-13 14:39
me too

**Comment by natto-maki** [comment] 2024-01-17 04:20
Thank you for your feedback.
Release v0.3.2 fixes a bug related to import, so please check with the latest version.
Note: requirements.txt has been updated.

Please comment if the problem is still not resolved. Or, I will close this issue after a week has passed.

**Closed as completed** 2024-01-23 16:47 UTC
Labels: bug
