### ISSUE TITLE
module 'openai' has no attribute 'OpenAI'

### ISSUE THREAD

**Issue by jammyfu** [natto-maki/ComfyUI-NegiTools#2] opened 2023-12-11 14:08 UTC
I successfully installed the openai package, but the execution failed with an error: "module 'openai' has no attribute 'OpenAI'
![image](https://github.com/natto-maki/ComfyUI-NegiTools/assets/1559847/e5fcafaa-9ebe-48e9-9eb4-d13a56aa747b)

**Comment by natto-maki** [comment] 2023-12-13 10:46
Is it possible to check the version of the 'openai' package?
i.e., pip list | grep openai

If you have a version of 0.x.x installed, this is most likely the cause of the problem.

The 'openai' package has a different interface between 0.x.x and 1.x.x. The installation instructions in the old README did not specify the version of the 'openai' package, so this may have caused an older version to be installed.
The latest installation procedure has changed to using requirements.txt, and it can be expected that the proper version will be installed.

**Comment by natto-maki** [comment] 2024-01-05 12:55
Probably resolved in the version that provides requirements.txt

**Comment by natto-maki** [comment] 2024-01-05 12:56
Probably resolved in the version that provides requirements.txt

**Closed as not planned by natto-maki** 2024-01-05 12:56 UTC
Labels: duplicate
