### ISSUE TITLE
Cannot Load the Nodes

### ISSUE THREAD

**Issue by Piscabo** [natto-maki/ComfyUI-NegiTools#5] opened 2023-12-27 18:16 UTC
When installing I get this? I can't find any error in the load log apart from this:
Traceback (most recent call last):
  File "H:\AI_Files\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\AI_Files\ComfyUI\custom_nodes\ComfyUI-NegiTools\__init__.py", line 8, in <module>
    from .negi.open_pose_to_point_list import OpenPoseToPointList
  File "H:\AI_Files\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\open_pose_to_point_list.py", line 6, in <module>
    from controlnet_aux import OpenposeDetector
ImportError: cannot import name 'OpenposeDetector' from 'controlnet_aux' (H:\AI_Files\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\__init__.py)

Cannot import H:\AI_Files\ComfyUI\custom_nodes\ComfyUI-NegiTools module for custom nodes: cannot import name 'OpenposeDetector' from 'controlnet_aux' (H:\AI_Files\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\__init__.py)
![image](https://github.com/natto-maki/ComfyUI-NegiTools/assets/123719842/08a959cf-eb31-4706-8935-40fd286391ca)
![image](https://github.com/natto-maki/ComfyUI-NegiTools/assets/123719842/0120ec57-83f2-4e2e-8e17-afe6798c9087)
Any help on this?
I have checked that the requirements are installed...

**Comment by natto-maki** [comment] 2023-12-28 13:49
Please try v0.3.1
This version changes to call a copy of controlnet_aux, which is expected to avoid conflicts with controlnet_aux, which comfyui_controlnet_aux has built in.

Please comment if the problem is still not resolved. Or, I will close this issue after a week has passed.

**Comment by Piscabo** [comment] 2023-12-29 21:13
> Please try v0.3.1 This version changes to call a copy of controlnet_aux, which is expected to avoid conflicts with controlnet_aux, which comfyui_controlnet_aux has built in.
> 
> Please comment if the problem is still not resolved. Or, I will close this issue after a week has passed.

Encounter new problem:
Traceback (most recent call last):
  File "H:\AI_Files\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\AI_Files\ComfyUI\custom_nodes\ComfyUI-NegiTools\__init__.py", line 8, in <module>
    from .negi.open_pose_to_point_list import OpenPoseToPointList
  File "H:\AI_Files\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\open_pose_to_point_list.py", line 6, in <module>
    from .repos.controlnet_aux.src.controlnet_aux import OpenposeDetector
  File "H:\AI_Files\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\repos\controlnet_aux\src\controlnet_aux\__init__.py", line 4, in <module>
    from .leres import LeresDetector
  File "H:\AI_Files\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\repos\controlnet_aux\src\controlnet_aux\leres\__init__.py", line 13, in <module>
    from .pix2pix.models.pix2pix4depth_model import Pix2Pix4DepthModel
ModuleNotFoundError: No module named 'ComfyUI-NegiTools.negi.repos.controlnet_aux.src.controlnet_aux.leres.pix2pix.models'

Cannot import H:\AI_Files\ComfyUI\custom_nodes\ComfyUI-NegiTools module for custom nodes: No module named 'ComfyUI-NegiTools.negi.repos.controlnet_aux.src.controlnet_aux.leres.pix2pix.models'

![image](https://github.com/natto-maki/ComfyUI-NegiTools/assets/123719842/8c0be223-612b-454f-95f3-24709a95f5d0)

**Comment by silvbb** [comment] 2024-01-16 07:41
me,too

**Comment by natto-maki** [comment] 2024-01-17 04:20
Thank you for your feedback.
Release v0.3.2 fixes a bug related to import, so please check with the latest version.
Note: requirements.txt has been updated.

Please comment if the problem is still not resolved. Or, I will close this issue after a week has passed.

**Closed as completed** 2024-01-23 16:47 UTC
Labels: bug
