### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by cjh1228** [natto-maki/ComfyUI-NegiTools#7] opened 2024-01-03 07:44 UTC
2024-01-03 15:40:18.631523 Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools\__init__.py", line 8, in <module>
    from .negi.open_pose_to_point_list import OpenPoseToPointList
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\open_pose_to_point_list.py", line 6, in <module>
    from .repos.controlnet_aux.src.controlnet_aux import OpenposeDetector
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\repos\controlnet_aux\src\controlnet_aux\__init__.py", line 4, in <module>
    from .leres import LeresDetector
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools\negi\repos\controlnet_aux\src\controlnet_aux\leres\__init__.py", line 13, in <module>
    from .pix2pix.models.pix2pix4depth_model import Pix2Pix4DepthModel
ModuleNotFoundError: No module named 'ComfyUI-NegiTools.negi.repos.controlnet_aux.src.controlnet_aux.leres.pix2pix.models'

2024-01-03 15:40:18.631523 Cannot import D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools module for custom nodes: No module named 'ComfyUI-NegiTools.negi.repos.controlnet_aux.src.controlnet_aux.leres.pix2pix.models'

**Comment by natto-maki** [comment] 2024-01-05 12:51
Probably duplicate of #6

**Comment by natto-maki** [comment] 2024-01-17 04:21
Thank you for your feedback.
Release v0.3.2 fixes a bug related to import, so please check with the latest version.
Note: requirements.txt has been updated.

Please comment if the problem is still not resolved. Or, I will close this issue after a week has passed.

**Closed as completed** 2024-01-23 16:47 UTC
Labels: duplicate

**Comment by madmanswork** [comment] 2024-03-21 19:12
I can't import ComfyUI-NegiTools. I've tried it through the manager, cloning it and manually dumping it. I've done all requirement it asks me.  (IMPORT FAILED) [ComfyUI-NegiTools](https://github.com/natto-maki/ComfyUI-NegiTools)
